# Docker compose https://docs.docker.com/compose/compose-file/
# First, create the "blog_dev" network with this command:
# $ docker network create --driver bridge blog_dev

version: "3.9"
name: 'plainblog'

services:

  blog-db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"  # HostPort:ContainerPort - Expose port 5433 to connect when using VisualStudio
    networks:
      - blog_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: blog_database
    volumes:
      - postgres-data-blog:/var/lib/postgresql/data

  blog-api:
    build:
        context: ../src
        dockerfile: ../deploy/server/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - blog-db
    networks:
      - blog_dev
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"     # Development mode to run EF Migrations automatically. Not suitable for production
      ConnectionStrings__PlainBlogContext: "Server=blog-db;User Id=postgres;Password=example;Database=blog_database;Port=5432;TrustServerCertificate=True"

networks:
  blog_dev:
    driver: bridge

volumes:  
  postgres-data-blog:
    driver: local