@PlainBlog.Application_HostAddress = http://localhost:5183
#@PlainBlog.Application_HostAddress = http://app.plainblog.local

### Get Posts in json
GET {{PlainBlog.Application_HostAddress}}/api/post
Accept: application/json



### Get Posts in xml
GET {{PlainBlog.Application_HostAddress}}/api/post
Accept: application/xml



### Get post by id
GET {{PlainBlog.Application_HostAddress}}/api/post/1
Accept: application/json



### Get post by id including author data
GET {{PlainBlog.Application_HostAddress}}/api/post/1?includeAuthor=true
Accept: application/json




### Create a new blog post using json
POST {{PlainBlog.Application_HostAddress}}/api/post
Content-Type: application/json
Accept: application/json

{
  "authorId": 1,
  "title": "Title6",
  "description": "Descriptionn6",
  "content": "content6"
}

###

### Create a new blog post using xml
POST {{PlainBlog.Application_HostAddress}}/api/post
Content-Type: application/xml
Accept: application/xml

<PostSave>
    <AuthorId>1</AuthorId>
    <Title>Title999</Title>
    <Description>Descriptionn99</Description>
    <Content>content99</Content>
</PostSave>