name: CI

on:
  push:
    branches:
      - main  # Trigger CI on push to the main branch
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore src/PlainBlog.Application.sln

    - name: Build
      run: dotnet build src/PlainBlog.Application.sln --configuration Release

    - name: Test and upload coverage for all test projects
      run: dotnet test src/PlainBlog.Application.sln --configuration Release --collect:"XPlat Code Coverage"
      # run: |
      #   for project in $(find src -type f -name "*Tests.csproj"); do
      #     project_dir=$(dirname "$project")
      #     dotnet test "$project" --configuration Release --collect:"XPlat Code Coverage"
      #     mv "$project_dir/TestResults" "$project_dir/coverage"
      #   done
      # continue-on-error: true
      
    # - name: Upload coverage reports for all test projects
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: all-test-coverage
    #     path: src/**/coverage

    # - name: Merge coverage reports
    #   run: |
    #     dotnet tool install -g dotnet-reportgenerator-globaltool
    #     reportgenerator "-reports:src/**/coverage.cobertura.xml" "-targetdir:merged_coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: src/**/**/coverage.cobertura.xml
        slug: evaristovidal/plainblog
