name: CI

on:
  push:
    branches:
      - main  # Trigger CI on push to the main branch
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore src/PlainBlog.Application.sln

    - name: Build
      run: dotnet build src/PlainBlog.Application.sln --configuration Release

    - name: Test and upload coverage for all test projects
      run: dotnet test src/PlainBlog.Application.sln --configuration Release --settings "src/CodeCoverage.runsettings" --collect:"XPlat Code Coverage" --results-directory:"TestResults" \

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: TestResults

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: TestResults
        slug: evaristovidal/plainblog
